import os
from markdown import markdown

class Report:
    def __init__(self):
        os.makedirs("out", exist_ok=True)

    def build_markdown_report(self, data):
        content = "# Rekap Nilai Mahasiswa\n\n"
        content += "| NIM | Nama | Hadir (%) | Quiz | Tugas | UTS | UAS | Nilai Akhir |\n"
        content += "|-----|------|------------|------|--------|-----|-----|-------------|\n"
        for mhs in data:
            content += f"| {mhs['nim']} | {mhs['nama']} | {mhs['hadir']} | {mhs['quiz']} | {mhs['tugas']} | {mhs['uts']} | {mhs['uas']} | {mhs['nilai_akhir']} |\n"
        content += "\nGenerated by student_performance_tracker"
        return content

    def save_text(self, filename, content):
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)

    def save_html(self, filename, data):
        html_content = self.build_markdown_report(data)
        html = markdown(html_content)
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html)
