import os
from markdown import markdown

class Report:
    def __init__(self):
        os.makedirs("out", exist_ok=True)

    def build_markdown_report(self, data):
        content = "# Rekap Nilai Mahasiswa\n\n"
        content += "| NIM | Nama | Hadir (%) | Quiz | Tugas | UTS | UAS | Nilai Akhir |\n"
        content += "|-----|------|------------|------|--------|-----|-----|-------------|\n"
        for mhs in data:
            content += (
                f"| {mhs['nim']} | {mhs['nama']} | {mhs['hadir']} | {mhs['quiz']} "
                f"| {mhs['tugas']} | {mhs['uts']} | {mhs['uas']} | {mhs['nilai_akhir']} |\n"
            )
        content += "\nGenerated by student_performance_tracker"
        return content

    def save_text(self, filename, content):
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)

    def save_html(self, filename, data):
        # Bangun tabel HTML manual agar bisa dikasih warna
        html_content = """
        <html>
        <head>
            <meta charset='UTF-8'>
            <title>Rekap Nilai Mahasiswa</title>
            <style>
                body { font-family: Arial, sans-serif; background-color: #f8f9fa; padding: 20px; }
                h1 { color: #007bff; }
                table { border-collapse: collapse; width: 100%; background: white; }
                th, td { border: 1px solid #ccc; padding: 8px; text-align: center; }
                th { background-color: #007bff; color: white; }
                tr:nth-child(even) { background-color: #f2f2f2; }
                .green { background-color: #d4edda; color: #155724; font-weight: bold; }
                .blue { background-color: #cce5ff; color: #004085; font-weight: bold; }
                .red { background-color: #f8d7da; color: #721c24; font-weight: bold; }
            </style>
        </head>
        <body>
            <h1>Rekap Nilai Mahasiswa</h1>
            <table>
                <tr>
                    <th>NIM</th>
                    <th>Nama</th>
                    <th>Hadir (%)</th>
                    <th>Quiz</th>
                    <th>Tugas</th>
                    <th>UTS</th>
                    <th>UAS</th>
                    <th>Nilai Akhir</th>
                </tr>
        """

        for mhs in data:
            # Tentukan warna berdasarkan nilai akhir
            if mhs["nilai_akhir"] >= 80:
                warna = "green"
            elif mhs["nilai_akhir"] >= 70:
                warna = "blue"
            else:
                warna = "red"

            html_content += f"""
                <tr>
                    <td>{mhs['nim']}</td>
                    <td>{mhs['nama']}</td>
                    <td>{mhs['hadir']}</td>
                    <td>{mhs['quiz']}</td>
                    <td>{mhs['tugas']}</td>
                    <td>{mhs['uts']}</td>
                    <td>{mhs['uas']}</td>
                    <td class='{warna}'>{mhs['nilai_akhir']}</td>
                </tr>
            """

        html_content += """
            </table>
            <p><i>Generated by student_performance_tracker</i></p>
        </body>
        </html>
        """

        with open(filename, "w", encoding="utf-8") as f:
            f.write(html_content)
